Добавляет данные из json
htmlacademy-vue/1518577-pizza-1 pull request #1
Opened 2022-04-05 14:23 UTC by TSergey123

2022-04-05 15:14 UTC, Djaler requested changes

2022-04-05 15:14 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    <div v-for="misc in miscs" :key="misc.id">
нужно не просто вывести данные из json.
В этом задании нужно перенести верстку страницы конструктора (template/src/main.html), реализовав вывод данных о вариантах теста, размера, соуса и ингредиентах с помощью v-for из json-данных

2022-04-06 18:36 UTC, Djaler commented on src/frontend/src/static/pizza.json
> +      "value": "light"
добавлять данные в исходный json нельзя, потому что именно в таком виде в дальнейшем будут приходить данные с сервера. тебе нужно дополнить эти данные с помощью хелперов. пример можно посмотреть в учебном проекте https://github.com/htmlacademy-vue/VueWork/blob/v1/src/frontend/src/common/helpers.js#L29

2022-04-06 18:37 UTC, merged

2022-04-07 14:48 UTC, TSergey123 commented on src/frontend/src/static/pizza.json
> +      "value": "light"
А могу я использовать this.$set?
Вот только не знаю как указать там значение из объекта. Хотел как-то так
`    this.$set(this.pizzas.dough[(this.name = "Тонкое")], "value", "light");
`

2022-04-07 17:49 UTC, Djaler commented on src/frontend/src/static/pizza.json
> +      "value": "light"
пока не совсем понял твою задумку. Ты наверное хочешь дополнить уже существующие в компоненте данные в каком-нибудь created?
Лучше сразу в data объявлять преобразованные в нужном виде данные. Вот как тут https://github.com/htmlacademy-vue/VueWork/blob/v1/src/frontend/src/views/Index.vue#L150